more changes

diff --git a/zpreztorc b/zpreztorc
--- a/zpreztorc
+++ b/zpreztorc
@@ -88,7 +88,7 @@ zstyle ':prezto:module:editor' key-bindings 'vi'
 # Set the prompt theme to load.
 # Setting it to 'random' loads a random theme.
 # Auto set to 'off' on dumb terminals.
-zstyle ':prezto:module:prompt' theme 'paradox'
+zstyle ':prezto:module:prompt' theme 'steeef'
 
 #
 # Ruby
@@ -179,11 +179,56 @@ function mx()
 function vimgitshow() { 
 git show "$1" | vim - "+set filetype=${1##*.}";
 }
+function proxy_on() {
+    export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
+
+    if (( $# > 0 )); then
+        valid=$(echo $@ | sed -n 's/\([0-9]\{1,3\}\.\)\{3\}\([0-9]\{1,3\}\)\{1\}:\([0-9]\+\)/&/p')
+        if [[ $valid != $@ ]]; then
+            >&2 echo "Invalid address"
+            return 1
+        fi
+
+        export http_proxy="http://$1/"
+        export https_proxy=$http_proxy
+        export ftp_proxy=$http_proxy
+        export rsync_proxy=$http_proxy
+        echo "Proxy environment variable set."
+        return 0
+    fi
+
+    echo -n "username: "; read username
+    if [[ $username != "" ]]; then
+        echo -n "password: "
+        read -es password
+        local pre="$username:$password@"
+    fi
+
+    echo -n "server: "; read server
+    echo -n "port: "; read port
+    export http_proxy="http://$pre$server:$port/"
+    export https_proxy=$http_proxy
+    export ftp_proxy=$http_proxy
+    export rsync_proxy=$http_proxy
+    export HTTP_PROXY=$http_proxy
+    export HTTPS_PROXY=$http_proxy
+    export FTP_PROXY=$http_proxy
+    export RSYNC_PROXY=$http_proxy
+}
+
+function proxy_off(){
+    unset http_proxy
+    unset https_proxy
+    unset ftp_proxy
+    unset rsync_proxy
+    echo -e "Proxy environment variable removed."
+}
 #switch keyboard layout to internal
 function intkey(){
-sudo cp ~/dotfiles/intkey.layout /usr/share/X11/xkb/symbols/pc
-sudo rm -rf /var/lib/xkb/*
-sudo pkill X
+setxkbmap -layout us
+rm -f ~/.Xmodmap
+ln -s ~/dotfiles/intkey.Xmodmap ~/.Xmodmap
+xmodmap ~/.Xmodmap
 }
 #switch keyboard layout to logitech k200
 function logikey(){
@@ -197,7 +242,7 @@ sudo cp ~/dotfiles/tvskey.layout /usr/share/X11/xkb/symbols/pc
 sudo rm -rf /var/lib/xkb/*
 sudo pkill X
 }
-export VISUAL=vim
+export VISUAL=nvim
 export EDITOR="$VISUAL"
 alias ltr="ls -ltr"
 alias ltra="ls -ltra"
@@ -205,17 +250,17 @@ alias md="mkdir"
 alias c="clear"
 alias x="exit"
 alias m="man"
-alias v="vim"
+alias v="nvim"
 alias a="atom"
 alias s="sudo"
-alias vo="vim -O"
-alias vimrc="vim ~/.vimrc"
-alias zpreztorc="vim ~/.zpreztorc"
-alias zshrc="vim ~/.zshrc"
-alias bashrc="vim ~/.bashrc"
-alias tmux.conf="vim ~/.tmux.conf"
-alias i3config="vim ~/.i3/config"
-alias sv="sudo vim"
+alias vo="nvim -O"
+alias vimrc="nvim ~/.vimrc"
+alias zpreztorc="nvim ~/.zpreztorc"
+alias zshrc="nvim ~/.zshrc"
+alias bashrc="nvim ~/.bashrc"
+alias tmux.conf="nvim ~/.tmux.conf"
+alias i3config="nvim ~/.i3/config"
+alias sv="sudo nvim"
 alias reb="sudo shutdown -r now"
 alias shu="sudo shutdown -h now"
 alias dimon="xrandr --output eDP1 --off; xrandr --output LVDS1 --off"
@@ -226,5 +271,5 @@ alias go="gnome-open"
 # added by Anaconda2 2.4.0 installer
 export PATH="/home/harish/anaconda2/bin:$PATH"
 # source z.sh
-. ~/z/z.sh
+. /usr/share/z/z.sh
 
